name: makuira_gestion
description: App de gestión para el Club Makuira Sub-20 (DT y jugadores).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.10.0
  firebase_auth: ^6.7.0
  firebase_core: ^4.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Variable.ttf
          weight: 400
        - asset: assets/fonts/Archivo-Variable.ttf
          weight: 600
        - asset: assets/fonts/Archivo-Variable.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
